// src/pages/recipes/Recipes.svelte
<script lang="ts">
  import { get, writable, derived } from "svelte/store";
  import type { RecipesRoute } from "../../route";
  import { route, replaceRoute } from "../../route";
  import type { Recipe } from "../../models";
  import { getRecipes } from "../../api";
  import LoadingBar from "../../components/LoadingBar.svelte";
  import FilterRecipes from "./FilterRecipes.svelte";
  import RecipePanel from "./RecipePanel.svelte";

  let status = "loading";

  const recipes = writable<Recipe[]>([]);
  const allTags = writable<string[]>([]);

  getRecipes().then((result) => {
    if (result.status === "success") {
      recipes.set(result.data.recipes);
      allTags.set(result.data.recipeTags);
      status = "loaded";
    } else {
      status = result.error;
    }
  });

  const name = derived(route, ($route) => ($route as RecipesRoute).name);
  const tags = derived(route, ($route) => ($route as RecipesRoute).tags);

  function setName(name: string) {
    replaceRoute({ page: "recipes", tags: get(tags), name });
  }

  function setTags(tags: string[]) {
    replaceRoute({ page: "recipes", tags, name: get(name) });
  }

  function toggleTag(tag: string) {
    const currentTags = get(tags) || [];
    if (currentTags.includes(tag)) {
      setTags(currentTags.filter((t) => t !== tag));
    } else {
      setTags([...currentTags, tag]);
    }
  }

  let expandedRecipes: string[] = [];

  function toggleRecipeExpanded(recipeName: string) {
    if (expandedRecipes.includes(recipeName)) {
      expandedRecipes = expandedRecipes.filter((r) => r !== recipeName);
    } else {
      expandedRecipes = [...expandedRecipes, recipeName];
    }
  }

  const visibleRecipes = derived([route, recipes], ([$route, $recipes]) => {
    const $r = $route as RecipesRoute;
    const lowerName = ($r.name || "").toLowerCase();

    return $recipes.filter(
      (recipe) =>
        recipe.name.toLowerCase().includes(lowerName) &&
        ($r.tags || []).every((t) => recipe.tags.includes(t))
    );
  });

  const queryFilled = derived(route, ($route) => {
    const $r = $route as RecipesRoute;
    return $r.name || $r.tags?.length;
  });
</script>

<div class="container container-small">
  <div class="row">
    <div class="col align-center">
      <h1>Recipes</h1>
      <section>
        {#if status === 'loading'}
          <LoadingBar />
        {:else if status !== 'loaded'}
          <p class="alert alert-danger">{status}</p>
        {:else}
          <p>
            Between a book full of family recipes and my ever-growing rotation
            of Keto-friendly recipes, I needed somewhere to keep these that I
            could access from anywhere. With the power of YAML files and
            GraphQL, I can now check the ingredients on my phone at Trader Joe's
            before I check out, and you can, too!
          </p>
          <FilterRecipes allTags={$allTags} {toggleTag} {setName} />
          {#if $visibleRecipes.length}
            <div>
              <strong>
                {`${$visibleRecipes.length} recipe${$visibleRecipes.length === 1 ? '' : 's'}`}
                found:
              </strong>
              {#each $visibleRecipes as recipe}
                <RecipePanel
                  {recipe}
                  {toggleTag}
                  tags={$tags || []}
                  expanded={expandedRecipes.includes(recipe.name)}
                  toggleExpanded={() => toggleRecipeExpanded(recipe.name)} />
              {/each}
            </div>
          {:else}
            <p>
              <i>
                {#if $queryFilled}
                  No recipes found for the given query.
                {:else}No recipes available.{/if}
              </i>
            </p>
          {/if}
        {/if}
      </section>
    </div>
  </div>
</div>

// src/routes/recipes.tsx
import { createMemo, createSignal, For, Show } from "solid-js";
import { Title, useParams, useRouteData, useSearchParams } from "solid-start";
import { createServerData } from "solid-start/server";
import RecipePanel from "~/components/recipes/RecipePanel";
import TagList from "~/components/recipes/TagList";
import { Recipe } from "~/types/recipe";
import { toggleInList } from "~/utils";

export default function RecipesPage() {
  const [recipes] = createTrpcQ
  const [expanded, setExpanded] = createSignal<string[]>([]);
  const [searchParams, setSearchParams] = useSearchParams()

  const tags = createMemo(() => (useParams()["tags"] ?? "").split(","));
  const queryFilled = createMemo(() => searchParams.name || searchParams.tags)

  const recipes = useRouteData<typeof routeData>()
  const allTags = createMemo(() => [...new Set((recipes() || []).flatMap(recipe => recipe.tags))])

  const visibleRecipes = createMemo(() => {
    const lowerName = (searchParams.name || "").toLowerCase()

    return (recipes() || []).filter(recipe => {
      recipe.name.toLowerCase().includes(lowerName) &&
        tags().every((t) => recipe.tags.includes(t))
    })
  })

  function toggleTag(tag: string) {
    setSearchParams({ ...searchParams, tags: toggleInList(tags(), tag).join(",") })
  }

  return (
    <main>
      <Title>Recipes - Sam Mohr</Title>
      <div class="container">
        <div class="grid">
          <div>
            <h1>Recipes</h1>
            <p>
              Between a book full of family recipes and my ever-growing rotation
              of Keto-friendly recipes, I needed somewhere to keep these that I
              could access from anywhere. With the power of YAML files and
              GraphQL, I can now check the ingredients on my phone at Trader Joe's
              before I check out, and you can, too!
            </p>

            <section>
              <Show when={recipes()} fallback={<article aria-busy="true" />}>
                <fieldset>
                  <legend>Filter Recipes</legend>
                  <div class="form-control">
                    <label>By Name
                      <input
                        type="text"
                        placeholder="Meatball Mania"
                        value={searchParams.name || ''}
                        onInput={(event) => setSearchParams({
                          ...searchParams,
                          name: event.currentTarget.value,
                        })}
                      />
                    </label>
                  </div>
                  <div class="form-control">
                    <label>By Tag</label>
                    <TagList tags={allTags()} selected={tags()} toggle={toggleTag} />
                  </div>
                </fieldset>

                {visibleRecipes().length > 0 ? (
                  <div>
                    <strong>
                      {`${visibleRecipes().length} recipe${visibleRecipes().length === 1 ? '' : 's'}`}
                      found:
                    </strong>
                    <For each={visibleRecipes()}>
                      {(recipe) => (
                        <RecipePanel
                          recipe={recipe}
                          toggleTag={toggleTag}
                          selectedTags={tags()}
                          expanded={expanded().includes(recipe.name)}
                          toggleExpanded={() => setExpanded(toggleInList(expanded(), recipe.name))}
                        />
                      )}
                    </For>
                  </div>
                ) : (
                  <p>
                    <i>
                      {queryFilled() ?
                        "No recipes found for the given query." :
                        "No recipes available."
                      }
                    </i>
                  </p>
                )}
              </Show>
            </section>
          </div>
        </div>
      </div>
    </main>
  )
}
