// src/components/recipes/TagList.tsx
import { For, mergeProps } from "solid-js";

export default function TagList(props: {
  tags: string[],
  selected: string[],
  toggle: (tag: string) => void,
  rightAlign?: boolean,
}) {
  const merged = mergeProps(props, { rightAlign: false });

  return (
    <ul class={`tags ${merged.rightAlign ? 'right' : ''}`}>
      <For each={merged.tags}>
        {tag => (
          <li
            class={`tag tag-rounded${merged.selected.includes(tag) ? ' tag-green' : ''}`}
            onClick={() => merged.toggle(tag)}>
            {tag}
          </li>
        )}
      </For>
    </ul>
  )
}

// src/lib/components/TagList.svelte
<script lang="ts">
  export let tags: string[];
  export let selected: string[];
  export let toggle: (tag: string) => void;
  export let rightAlign: boolean = false;
</script>

<span class:justify-end={rightAlign}>
  {#each tags as tag}
    <span
      class="chip hover:cursor-pointer {selected.includes(tag) ? 'variant-filled' : 'variant-soft'}"
      on:click={() => toggle(tag)}
    >
      {tag}
  	</span>
  {/each}
</span>
